##Problem 2
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
#By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
#find the sum of the even-valued terms.

################################################################################
library(ggplot2)
library(rsconnect)
library(readxl)
library(dplyr)
library(psych)
library(data.table)
library(caret)
library(corrplot)
library(pROC)
library(magick)
library(fmsb)
# Set graphic colors
library(RColorBrewer)
library(scales)
library(rgl)
library(car)

# Clear environment
rm(list=ls()) 

#Working directory
getwd()
setwd("C:\\Users\\dwive\\Documents\\")

set.seed(8068)

div1 = 2

n = 10000
fib = list(1,2)
max_fib = 4000000

for (x in 3:n) {
  print(x)
  #print(fib[x-1])
  #print(fib[x-2])
  if (fib[[x-1]]+fib[[x-2]]>max_fib) 
    { break }
    else 
      {  fib[[x]] = fib[[x-1]]+fib[[x-2]] }
  }

print(fib)

sum = 0
for (x in 1:length(fib)) {
  if (fib[[x]]%%div1 ==0 ) 
  { sum = sum + fib[[x]] }
  else 
  {  next }
}


print(sum)

#Reduce("+", fib)
